events {}

http {

    upstream users {
        server user-service:8080;
    }

    upstream bookings {
        server booking-service:8080;
    }

    upstream search {
        server search-service:8000;
    }

    server {
        listen 80;

        location /api/users {
            proxy_pass http://users;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /api/search {
                    proxy_pass http://search;

                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                }

        location /api/bookings{
            proxy_pass  http://bookings;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}