spring:
  application:
    name: hotel

  datasource:
    url: jdbc:postgresql://postgres:5432/hotel
    username: postgres
    password: password
#    url: jdbc:postgresql://localhost:5432/hotel
#    username: postgres
#    password: Karthik@05


  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
