spring:
  application:
    name: hotel

  datasource:
    url: jdbc:postgresql://localhost:5432/sandipsaha
#      url: jdbc:postgresql://postgres:5432/hotel
    username: sandipsaha
#      username: postgres
    password: Biltu@123
#      password: password

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect